// KEP v5.5 — Supabase Edge Function: kep-ai-review
// Safe backend bridge for AI review suggestions.
// This function keeps AI API keys on the server side and checks the user role before returning suggestions.

import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

type ReviewInput = {
  content_type?: string;
  subject?: string;
  question?: string;
  options?: string[];
  correct_answer?: string;
  explanation?: string;
  source?: string;
  language?: string;
};

function jsonResponse(body: unknown, status = 200) {
  return new Response(JSON.stringify(body, null, 2), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function wordCount(text = "") {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function localSuggestion(input: ReviewInput) {
  const issues: string[] = [];
  const strengths: string[] = [];
  const options = Array.isArray(input.options) ? input.options.filter(Boolean) : [];
  const question = input.question || "";

  if (!question) issues.push("Question text is empty.");
  if (question && wordCount(question) < 5) issues.push("Question may be too short or unclear.");
  if (question && wordCount(question) > 45) issues.push("Question may be too long.");
  if (question && !/[?؟]$/.test(question.trim())) issues.push("Question does not end with a question mark.");
  if (options.length < 4) issues.push("Question should usually have 4 answer options.");
  if (new Set(options.map((x) => x.toLowerCase().trim())).size !== options.length) issues.push("Some answer options look duplicated.");
  if (input.correct_answer && options.length && !options.some((x) => x.toLowerCase().trim() === input.correct_answer!.toLowerCase().trim())) {
    issues.push("Correct answer does not exactly match one of the options.");
  }
  if (!input.explanation || wordCount(input.explanation) < 8) issues.push("Explanation is missing or too short.");

  if (options.length >= 4) strengths.push("Question has enough options.");
  if (input.explanation && wordCount(input.explanation) >= 8) strengths.push("Explanation is present.");
  if (input.source) strengths.push("Source or reviewer note is included.");

  const difficulty =
    wordCount(question) > 35 ? "Hard" :
    wordCount(question) > 16 ? "Medium" :
    "Easy";

  const explanationDraft = input.explanation && wordCount(input.explanation) >= 8
    ? input.explanation
    : input.correct_answer
      ? `The correct answer is "${input.correct_answer}". A human reviewer should improve this explanation before publishing.`
      : "Add the correct answer first, then write a short student-friendly explanation.";

  const terms = question
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s]/gu, " ")
    .split(/\s+/)
    .filter((w) => w.length > 4)
    .slice(0, 8);

  return {
    mode: "local_backend_fallback",
    status: "ai_suggestion_only",
    safety_rule: "AI suggests. Human reviewer approves. Do not auto-publish.",
    suggestions: {
      quality: {
        score: Math.max(0, Math.min(100, 100 - issues.length * 15 + strengths.length * 5)),
        strengths,
        issues,
        reviewer_decision: issues.length ? "Needs human review before publishing" : "Looks ready for reviewer approval",
      },
      difficulty: {
        difficulty,
        reason: "Estimated by backend fallback rules. Real AI can improve this later.",
      },
      explanation_draft: explanationDraft,
      translation_drafts: {
        note: "Real translation drafts require an AI provider key and human review.",
        pashto_draft_placeholder: "Pashto draft will be generated by real AI when configured.",
        dari_draft_placeholder: "Dari draft will be generated by real AI when configured.",
      },
      duplicate_check: {
        search_terms: terms,
        action: "Search existing published questions using these terms before publishing.",
      },
    },
  };
}

function extractOutputText(result: any): string {
  if (typeof result?.output_text === "string") return result.output_text;
  const output = result?.output || [];
  for (const item of output) {
    const content = item?.content || [];
    for (const block of content) {
      if (typeof block?.text === "string") return block.text;
    }
  }
  return "";
}

async function openAiSuggestion(input: ReviewInput) {
  const apiKey = Deno.env.get("OPENAI_API_KEY");
  const model = Deno.env.get("OPENAI_MODEL");

  if (!apiKey || !model) return localSuggestion(input);

  const system = `You are KEP's education content review assistant.
Return only JSON. Do not publish content. Do not claim official Kankor rules.
A human reviewer must approve every suggestion.
Provide: quality score, issues, strengths, difficulty, explanation draft, translation placeholders, and duplicate search terms.`;

  const payload = {
    model,
    input: [
      { role: "system", content: system },
      { role: "user", content: JSON.stringify(input) },
    ],
    max_output_tokens: 900,
  };

  const res = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const message = await res.text();
    return {
      ...localSuggestion(input),
      mode: "local_backend_fallback_after_ai_error",
      ai_error: message.slice(0, 500),
    };
  }

  const result = await res.json();
  const text = extractOutputText(result);

  try {
    const parsed = JSON.parse(text);
    return {
      mode: "openai_backend",
      status: "ai_suggestion_only",
      safety_rule: "AI suggests. Human reviewer approves. Do not auto-publish.",
      suggestions: parsed,
    };
  } catch {
    return {
      mode: "openai_backend_text",
      status: "ai_suggestion_only",
      safety_rule: "AI suggests. Human reviewer approves. Do not auto-publish.",
      suggestions: {
        raw_text: text,
        note: "AI response was not valid JSON. Reviewer should read and edit manually.",
      },
    };
  }
}

async function getPublishableKey() {
  const legacy = Deno.env.get("SUPABASE_ANON_KEY");
  if (legacy) return legacy;

  const dict = Deno.env.get("SUPABASE_PUBLISHABLE_KEYS");
  if (dict) {
    const parsed = JSON.parse(dict);
    return parsed.default || Object.values(parsed)[0];
  }

  return "";
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return jsonResponse({ error: "Method not allowed" }, 405);
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const publishableKey = await getPublishableKey();
    const authHeader = req.headers.get("Authorization") || "";

    if (!supabaseUrl || !publishableKey) {
      return jsonResponse({ error: "Supabase environment variables are missing." }, 500);
    }

    if (!authHeader) {
      return jsonResponse({ error: "Login required." }, 401);
    }

    const supabase = createClient(supabaseUrl, publishableKey, {
      global: { headers: { Authorization: authHeader } },
    });

    const { data: userData, error: userError } = await supabase.auth.getUser();
    if (userError || !userData?.user) {
      return jsonResponse({ error: "Invalid or expired login session." }, 401);
    }

    const { data: profile, error: profileError } = await supabase
      .from("profiles")
      .select("role")
      .eq("id", userData.user.id)
      .single();

    if (profileError || !profile || !["admin", "reviewer"].includes(profile.role)) {
      return jsonResponse({ error: "Admin or reviewer role required." }, 403);
    }

    const body = await req.json();
    const input: ReviewInput = body?.input || body;

    if (!input?.question) {
      return jsonResponse({ error: "Question text is required." }, 400);
    }

    const suggestion = await openAiSuggestion(input);

    return jsonResponse({
      ok: true,
      user_role: profile.role,
      created_at: new Date().toISOString(),
      ...suggestion,
    });
  } catch (error) {
    return jsonResponse({ error: String(error?.message || error) }, 500);
  }
});
